### ISSUE TITLE
TurboRaketti doesn't work

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Minimig-AGA_MiSTer#131]
This TurboRaketti version used to work but works no more:

https://www.dropbox.com/s/50r0t9op1lqfunl/TurboRaketti_speedup.adf?dl=0

Could this be caused by a change in the MiSTer or Linux?

**Comment by sorgelig** [comment]
While providing such weird disk, it would be good to get instructions how to start it. And since Amiga has many configs/bioses, it should be mentioned too.
tested on config: KS3.1, WB3.1, ECS 1/2MB ChipRAM, 68000
DOS loaded from disk doesn't want to start none of 1, 2 or 3.
Started from WB - works. 
In AGA graphics is messed.

**Comment by dfilskov** [comment]
Got it - must be my WB installation then. Sorry -and thanks!
