### ISSUE TITLE
Kickstart version not being completely flushed when switching configs.

### ISSUE THREAD

**Issue by AegisPrime** [MiSTer-devel/Minimig-AGA_MiSTer#141]
Hi! I found this interesting oddity:

I have three Minimig configs: OS3.9 (KS 45.57), OS 3.2.1 (KS 47.102) and KS 1.3

By default I load OS3.9 - if I _then_ load OS3.2.1, it incorrectly reports the Kickstart version as **47.57** (seemingly taking the xx.57 from the prior Kickstart) - in order to correctly show KS 47.102 in OS3.2.1 I have to load the KS 1.3 config _before_ loading OS 3.2.1

This bug doesn't _appear_ to cause any issues with 3.2/3.2.1 (I don't think it cares so long as the KS version is v47+) but I'm guessing it _could_ if something checks the full version string?

**Comment by sorgelig** [comment]
This is how original Amiga works. While loading, OS may replace some functions with patches to KS by placing specific code into RAM then trigger reset, then next time Amiga boots it automatically pickup these patches from RAM. So you may see how power LED is dimmed for a while upon butting - it shows that Amiga is restarting several times in booting process.

**Comment by AegisPrime** [comment]
Sure, but on a real Amiga you wouldn't usually swap the Kickstart ROMs whilst the thing is powered on.

Given that a config can change the CPU, RAM, Chipset, Kickstart and HD, wouldn't it make sense to ensure the old system is completely flushed? I can't see any benefit to the user in the current behaviour?

**Comment by nretro** [comment]
You just have to write 0 to address 0 before the reset to discard any resident structures. Actually, this could be done automatically on loading kickstarts in minimig_config.cpp (Main_MiSTer). I'll have a look at it after the holidays.

**Comment by sorgelig** [comment]
i can add write 0 to address 0 if this is all required.

**Comment by AegisPrime** [comment]
That sounds great! Thank you both for looking into this!

**Comment by nretro** [comment]
Minor correction: writing 0x01 to address 0x04 will do the trick. An odd ExecBase pointer (which is always at 0x04) will be rejected immediately. The corresponding code (in Kickstart 1.2) is:

`FC014C  move.l    4,D0              Get pointer at location 4.`
`FC0150  btst      #0,D0             Check if it is an odd address.`
`FC0154  bne.s     FC01CE            Go reconfigure memory if it is.`
`FC0156  move.l    D0,A6             Assume we are pointing to ExecBase.`
`FC0158  add.l     $26(A6),D0        Get complement of ExecBase.`

(see http://wandel.ca/homepage/execdis/exec_disassembly.txt)

**Comment by nretro** [comment]
One more correction: to make the 32 bit address at 0x04 odd, we have to write the byte 0x01 at address 0x07, since m68k is big-endian. Sorry, I'm a little out of shape.

**Comment by sorgelig** [comment]
thanks for more info! i will make changes.

**Comment by nretro** [comment]
Thanks! While you are at it.. is there a reason, why Kickstart ROMs can only be selected from the Amiga directory? Used to be different and that's quite annoying, when you have more than 10 different versions. I reverted that change to 

  `SelectFile(Selected_F[4], "ROM", SCANO_DIR, MENU_MINIMIG_ROMFILE_SELECTED, MENU_MINIMIG_CHIPSET1);`

at `case MENU_MINIMIG_CHIPSET2:` in menu.cpp, adding the SCANO_DIR (instead of 0) option. 

Just a suggestion for the next release. For me, I can also just compile my own version.

**Comment by sorgelig** [comment]
> One more correction: to make the 32 bit address at 0x04 odd, we have to write the byte 0x01 at address 0x07, since m68k is big-endian. Sorry, I'm a little out of shape.

in motorola mode only bytes are swapped, not words, so it's byte at address 0x5, not 0x7. Anyway, i will simply write 0x01010101 at 0x4 :)

**Comment by nretro** [comment]
It does swap all bytes. So writing 0x01 to 0x7 (or 0x01010101)  is the right operation. Writing to 0x4 might not work for 68000, because this is just the top 8 bit of the address, which this CPU ignores.

Just to make sure, that it is in fact 0x7, I wrote a small program:
```
s:
	moveq	#0,d0
	moveq	#0,d1
	moveq	#0,d2
	moveq	#0,d3
	move.l	#$12345678,data
	move.b	data,d0
	move.b	data+1,d1
	move.b	data+2,d2
	move.b	data+3,d3
	rts

	ALIGN 0,4
data: dc.l 0
```

(Seka resp ASM-One syntax). Running this program results in D0=0x12 ... and D3= 0x78. If we want to ensure to get an odd address, we therefore have to write to data+3.

Edit: Some parts of what I have written above are of course not correct. I somehow interpreted 0x01010101 as 8 binary bits, but of course that is 4 bytes. So writing that to 0x04 definitely results in an odd 32 bit vector at that address.

**Comment by nretro** [comment]
After a reset, the minimig core does not allow to write to the lower 512KB, because of the line 
	`sel_chip[0] = cpu_address_in[23:19]==5'b0000_0 && !ovl;`
in gary.v. So currently, we can not write to 0x04 in minimig_config.cpp.
Changing above line to
`sel_chip[0] = cpu_address_in[23:19]==5'b0000_0 && (!ovl || cpu_hlt)`
should solve this issue. 

The minimig core probably does not support to write a single byte via spi, at least the corresponding code in userio.v suggest that:
	
```
        toggle <= ~btoggle;
	if(btoggle) begin
	host_wdat[7:0] <= IO_DIN[7:0];
	mrx <= 1;
	IO_WAIT <= 1;
	end
	else host_wdat[15:8] <= IO_DIN[7:0];
```
I haven't looked any further, since writing an odd number of bytes is not necessary.

**Comment by nretro** [comment]
OK... with that change in gary.v it works as expected. Entering the System -> ROM selector and a following reset will trigger a reload of the ROM and sets ExecBase at 0x04 to an odd address which will result in a cold reset and discard all resident structures.

**Comment by AegisPrime** [comment]
Hey nretro! Thanks so much for looking into this! Is it possible for me to implement this change myself or would it require a new bulild of the Minimig RBF? Thanks!

**Comment by sorgelig** [comment]
I was feeling the write didn't work as expected but had no time to check why. Thanks for pointing out.
As of byte write, it aggregates a word from consecutive spi data and writes a whole word, so this is not a problem.

**Comment by sorgelig** [comment]
this build should properly remove residents:
(removed)

**Comment by sorgelig** [comment]
Also tweaked Main to always upload kickstart and remove residents on config load regardless if KS is the same as before:
(removed)
before it KS was checked and skipped (and residents not removed) if the same.

**Comment by AegisPrime** [comment]
Perfect! Thank you you much @sorgelig and @nretro - just tested it and it works great! :)

**Comment by AegisPrime** [comment]
@sorgelig hey! Actually, on further testing, that new MiSTer.zip leaves me with a black screen on both my CRT and my HDMI monitors (the Minimig.zip seem to work fine though).

**Comment by sorgelig** [comment]
check video filters

**Comment by AegisPrime** [comment]
> check video filters

I'm not sure I follow? With that MiSTer.zip I can't get the F12 menu up? (no signal detected on HDMI/blank screen on CRT). Thanks!

**Comment by nretro** [comment]
Those files work for me.

**Comment by AegisPrime** [comment]
The Minimig,zip works fine - MiSTer,zip doesn't work at all for me though. I don't understand why it'd work on one MiSTer and not another? I've attached my MiSTer ini's below - anything in there that might be causing issues?
[MiSTer.txt](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/7833959/MiSTer.txt)
[MiSTer_alt_1.txt](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/7833960/MiSTer_alt_1.txt)
[MiSTer_alt_2.txt](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/7833961/MiSTer_alt_2.txt)

**Comment by sorgelig** [comment]
i can't tell by ini file. You can start from default ini and add/change options one by one.

**Comment by AegisPrime** [comment]
@sorgelig I did try a default config and my MiSTer still wasn't working with MiSTer.zip above, however, I just got a MiSTer and Minimig update (Minimig_20220108.rbf) which appears to have the fixes in it and that's working fine? The MiSTer update (08/01/2022) is 816,696 bytes and the one in the zip file above is 816,648 bytes.

**Comment by sorgelig** [comment]
Main from update is more recent.

**Comment by AegisPrime** [comment]
In that case, everything seems good :) Thanks again @sorgelig and @nretro!
